### ISSUE TITLE
How are you going to implement the getReg()?

### ISSUE THREAD

**Issue by sunzc** [sunzc/Compiler-Project#2]
For me, getReg() should be a bit complex. 
1) It need a context. Consider a function call func_a call func_b, the getReg() for func_a should be in different context with func_b, right?

2) and it should manage caller save registers as well as callee save registers.

**Comment by Arnab035** [comment]
getReg() according to me could return the next available register number from the pool available. I was planning to maintain a global variable -> that can increment its value every time getReg() is called -> this global variable will be separate for integer and float -> which I guess is clear to you.

yes for functions maintaining this getReg() may get complex--> because you are right different context is needed. But I was thinking if getReg() atleast start working for other expressions-> using this method. Then maybe it could be extended to functions also.

I was thinking to maintain a getReg() for each type of expression as of now.

**Comment by sunzc** [comment]
getReg() is very important for implement functions, cause we need to store callee save registers before use and push caller save registers before do function calls. I plan to implement a RegManager(Register Manager) class, every function needs a regMgr object to keep track the registers it use.

for getReg(), it will need two paramters, getReg(isCallerSave, isFloat). it will reture a number indicating the register number. The regMgr will keep track of the context info.

**Comment by sunzc** [comment]
Now the project is finished, it's safe to close this issue now.
